txt_outro:
    "DIMENSION-CONTROLLING FORT" 1
    "\"DOH\" HAS NOW BEEN" 1
    "DEMOLISHED, AND TIME" 1
    "STARTED FLOWING REVEVERSELY." 0
    "\"VAUS\" MANAGED TO ESCAPE" 1
    "FROM THE DISTORTED SPACE." 0
    "BUT THE REAL VOYAGE OF" 1
    "\"ARKANOID\" IN THE GALAXY" 1
    "HAS ONLY STARTED......" 0
    0
