txt_round_intro:
    "THE ERA AND TIME OF" 1
    "THIS STORY IS UNKNOWN" 0
    "AFTER THE MOTHERSHIP" 1
    "\"ARKANOID\" WAS DESTROYED," 1
    "A SPACECRAFT \"VAUS\"" 1
    "SCRAMBLED AWAY FROM IT." 0
    "BUT ONLY TO BE" 1
    "TRAPPED IN SPACE WARPED" 1
    "BY SOMEONE........" 0
    0
